name: github actions learning
on:
  push:
    branches:
      - main
      - dev

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - name: check java and mvn versions
        run: |
          java -version
          mvn --version
      - name: set artifact version
        run: |
          mvn versions:set -DnewVersion=${GITHUB_RUN_NUMBER}
          cat pom.xml
      - name: compile
        run: mvn clean compile
        continue-on-error: true
