name: github actions learning
on:
  push:
    branches:
      - main
      - dev

env:
  name: "venky"

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: test-step
        run: |
          echo $GITHUB_REF
          echo $GITHUB_ACTOR
          echo $GITHUB_WORKFLOW
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
          echo $GITHUB_WORKSACE
      - uses: actions/checkout@v4
        name: checkout
      - name: list files
        run: ls -al

