name: github actions learning
on:
  push:
    branches:
      - main
      - dev

env:
  name: "venky"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - name: check java and mvn versions
        run: |
          java -version
          mvn --version
      - name: compile
        run: mvn clean compile
