name: github actions learning
on:
  push:
    branches:
      - main
      - dev

env:
  name: "venky"

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout
      - name: check java and mvn version
        run: |
          java -version
          mvn version
